pipeline {
    agent any

    environment {
        APP_NAME         = 'OnlineExamSystem'
        APP_VERSION      = '1.0.0'
        INSTITUTION      = 'VIT Vellore'
        EXAM_DURATION    = '90'
        PASS_MARK        = '40'
        NEGATIVE_MARKING = 'true'
        NEGATIVE_RATIO   = '0.25'
        MAX_ATTEMPTS     = '1'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/aditya-raj-arora/online-exam-jenkins-lab-7.git'
            }
        }
        stage('Show App Info') {
            steps {
                echo "Building ${env.APP_NAME}, version ${env.APP_VERSION} for ${env.INSTITUTION}"
                echo "Exam duration: ${env.EXAM_DURATION} min | Pass mark: ${env.PASS_MARK}% | Negative marking: ${env.NEGATIVE_MARKING}"
            }
        }
        stage('Build') {
            steps {
                dir('project5-envvars') {
                    bat 'python -m py_compile app.py'
                }
                echo "${env.APP_NAME} version ${env.APP_VERSION} compiled successfully."
            }
        }
        stage('Run Exam Simulation') {
            steps {
                dir('project5-envvars') {
                    bat 'echo Batch step sees APP_NAME=%APP_NAME% and PASS_MARK=%PASS_MARK%'
                    bat 'python -u app.py'
                }
            }
        }
    }
}
